### ISSUE TITLE
REST API application/x-www-form-urlencoded charset property issue

### ISSUE THREAD

**Issue by wayne-chung** [icatproject/icat.server#149]
As per the bug report https://bugzilla.mozilla.org/show_bug.cgi?id=416178, firefox automatically appends "; charset=UTF-8" to the Content-Type header of application/x-www-form-urlencoded on xhr requests. 

This causes a problem because the ICAT REST api refuses to login if the charset property is specified in the content-type header and returns a 400 bad parameter error:

{ "code" : "BAD_PARAMETER", "message": "json must not be null" }

The issue was report as a jersey bug https://java.net/jira/browse/JERSEY-1978

It is currently not possible to login to icat via the REST API using topcatv2 on Firefox.

**Comment by wayne-chung** [comment]
Alternatively, adding an api that consume application/json should also work (default by angularjs $http.post)

@POST
@Path("session")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON) 

Jersey 2 (glassfish 4) seems happy with both Content-Type:application/json; charset=UTF-8 and Content-Type:application/json on the topcat backend.

**Comment by fisherab** [comment]
Have you found a work around for this please?

**Comment by wayne-chung** [comment]
No work around.
