### ISSUE TITLE
Lucene parameter/sample filtering does not work.

### ISSUE THREAD

**Issue by jodysalt** [icatproject/icat.server#159]
When I send something like the following to "lucene/data":

sessionId:adbaf62f-33fd-4b2d-9292-e31dbba6226c
query:{"target":"Investigation","parameters":[{"name":"forgottenlabel","lowerNumericValue":1,"upperNumericValue":2}]}
maxCount:300

I get the following response:

{"code":"INTERNAL","message":"class java.lang.NullPointerException null"}

**Comment by fisherab** [comment]
This is because units has not been set. The code has been changed to generate a BAD_PARAMETER exception with a sensible error message - and of course there is a new test.
