### ISSUE TITLE
entityManager query not working

### ISSUE THREAD

**Issue by jodysalt** [icatproject/icat.server#166]
The following query does not work (for 4.7.0-20160314.150313-3):

(Alex just tried installing it for ISIS)

"select investigation from Investigation investigation , investigation.investigationUsers as investigationUser , investigationUser.user as user where user.name = :user ORDER BY investigation.startDate desc limit 0, 50 include investigation.investigationInstruments.instrument"

**Comment by fisherab** [comment]
It reports: 
org.icatproject.IcatException_Exception: variable INVESTIGATION2 mentioned in    INCLUDE clause is not defined
which is untrue and will be fixed

**Comment by fisherab** [comment]
please ignore typo above
