### ISSUE TITLE
ICAT to create logout JMS call when session expires

### ISSUE THREAD

**Issue by Softey** [icatproject/icat.server#170]
From what I understand with the current ICAT logging behaviour is that if a user doesn't log out properly, then they are still seen as logged in as no logout JMS message is produced

For example:

- I login to TopCat.
- ICAT JMS Log created: operation login.
- I just close the browser TopCat is in.
- 2 hours later my sessionID is destroyed.
- No JMS logout message is created by the ICAT.

The behaviour I would like to see is that when the sessionID is destroyed that a JMS logout message is produced. There would obviously need to be some logic to check that the user isn't logged in under another sessionId.

For example:

-SessionId has expired.
-Retrieve name associated with expired sessionId.
-Remove sessionId from session table.
-Check the session table for that name and IFF they are not in the table then send out a JMS logout message.

This still isn't very accurate by any stretch but it will stop it from looking like users have been logged in for weeks when only they went onto TopCat for 10 minutes and just closed their browser down.

**Comment by fisherab** [comment]
I suggest that the dashboard might treat any user who has been inactive for a period of time (configurable of course) as being logged out. 

The only way I can see to solve it cleanly on the ICAT side is to provide a call to see if somebody, identified by their username  (the one normally preceded by a mnemonic) has a valid sessionId. Is there any security issue about making such a call publicly available with authn?

**Comment by fisherab** [comment]
I meant to say *without* authn

**Comment by fisherab** [comment]
The new call has been added
