### ISSUE TITLE
Query returns duplicate ids for icat 4.6.1

### ISSUE THREAD

**Issue by jodysalt** [icatproject/icat.server#179]
select distinct datafile.id from Datafile datafile , datafile.dataset as dataset , dataset.investigation as investigation , investigation.facility as facility where facility.id = 1 and investigation.name = 'NT11175' and investigation.id = 1010754770 and dataset.id = 1083896358 and UPPER(datafile.name) like concat('%', 'M8S8_2', '%')

**Comment by fisherab** [comment]
This is fixed in 4.7
