### ISSUE TITLE
[SOLVED]icat.server Install fails with "Initialization failed for Singleton GateKeeper"

### ISSUE THREAD

**Issue by tyggerjai** [icatproject/icat.server#188]
icat server 4.8.0 from https://repo.icatproject.org/site/icat/server/
OS: Centos6-64 (VM on VBox)
glassfish4.0
python2.7
[java_err.txt](https://github.com/icatproject/icat.server/files/762657/java_err.txt)

Creating the icat jdbc sources succeeds, but the deployment fails:
 `remote failure: Error occurred during deployment: Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton GateKeeper. Please see server.log for more details.`

The server log has a couple of hundred lines: 
`Exception while loading the app : javax.ejb.CreateException: Initialization failed for Singleton GateKeeper javax.ejb.CreateException: Initialization failed for Singleton GateKeeper at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:483) at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81) at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:654) at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:396) at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219) at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180) at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158) at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166) at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122) at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291) at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352) at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497) at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219) at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491) at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:527) at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:523) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:360) at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:522) at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546) at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1423) at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1500(CommandRunnerImpl.java:108) at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1762) at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1674) at org.glassfish.admin.rest.resources.admin.CommandResource.executeCommand(CommandResource.java:396) at org.glassfish.admin.rest.resources.admin.CommandResource.execCommandSimpInMultOut(CommandResource.java:234) at sun.reflect.GeneratedMethodAccessor202.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:125) at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152) at... `

**Comment by tyggerjai** [comment]
Log snapshot from an attempt to install:
![icat_glassfish](https://cloud.githubusercontent.com/assets/477716/22771081/ba044870-eee8-11e6-9ee7-1c17f5cbd70c.png)

**Comment by fisherab** [comment]
Deployment issues of this kind are generally better discussed on the icatgroup (http://groups.google.com/group/icatgroup) where more people will take notice. Meanwhile please show the contents of the icat.log file which will be in the same directory as the server.log

**Comment by tyggerjai** [comment]
Thanks, I'll check the group out. icat.log:
`2017-02-10 11:49:12,467 INFO [admin-listener(5)] LoggingConfigurator - Using logback default configuration
2017-02-10 11:49:12,480 INFO [admin-listener(5)] LoggingConfigurator - Version of eclipselink is 2.5.0
2017-02-10 11:49:12,492 INFO [admin-listener(5)] GateKeeper - Creating GateKeeper singleton
2017-02-10 11:49:12,502 INFO [admin-listener(5)] PropertyHandler - Property file icat.properties loaded
2017-02-10 11:49:12,507 ERROR [admin-listener(5)] PropertyHandler - class javax.naming.NamingException reports Lookup failed for 'java:global/authn.anon-1.1.1/ANON_Authenticator' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}
`

**Comment by tyggerjai** [comment]
Oh, that's actually quite informative. I think that gives me another place to look, thanks.

**Comment by tyggerjai** [comment]
Apparently I didn't have authn_anon deployed - I suspect I neglected to rebuild it when I reinstalled glassfish at some point.

With authn_anon deployed, icat now installs and deploys, closing this as user error .... 

Maybe change the message on a failed install to mention icat.log as well as server.log?
