### ISSUE TITLE
ICAT schema: extensions to support data publication workflows

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#200]
According to its own claim, ICAT is supposed to link “all aspects of the research chain from proposal through to publication”. At HZB, we recently started to draft our data publication workflow. We want to manage data publications with ICAT. But we found the current schema would need some extensions.

We assume that a data publication in general may comprise one or more `Datasets` or `Datafiles` that may or may not belong to a single `Investigation`. The content of a publication would therefore best be represented by a `DataCollection`. There is currently no suitable place in the schema to store the publication metadata related to a `DataCollection`.

For the publication metadata, taking [DataCite 4.0](https://schema.datacite.org/meta/kernel-4.0/index.html) as orientation, the following attributes would be needed:
- Doi,
- Creator and contributor (`User`),
- Title,
- Publisher (`Facility`),
- Dates: date of creation and date of publication (Date of creation may be derived from the related datasets),
- Resource type (“Dataset”),
- Subject: keyword, classification code, or key phrase.
- Related identifiers. Relevant relation types may include: “IsCitedBy”, “Cites”, “IsSupplementTo”, “IsPartOf”, “IsCompiledBy”, “IsDerivedFrom”, “IsSourceOf”.
- Description, e.g. abstract.
- Funding information.

In order to create a suitable place to store this information, I suggest to add the following new classes to the schema:

## `DataPublication`

Represent a data publication.

Constraint: `facility`, `doi`

Relationships:

Card | Class               | Field
-----|---------------------|---------------------
1,1  | Facility            | facility
1,1  | DataCollection      | content
0,*  | DataPublicationUser | dataPublicationUsers
0,*  | RelatedIdentifier   | relatedIdentifiers
0,*  | FundingReference    | fundingReferences

Other fields:

Field           | Type
----------------|---------------------
doi             | String[255] NOT NULL
title           | String[255] NOT NULL
publicationDate | Date NOT NULL
subject         | String[1023]
description     | String[4000]

## `DataPublicationUser`

Author: creator of a or contributor to a data publication

Constraint: `publication`, `user`, `contributorType` 

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication
1,1  | User            | user

Other fields:

Field           | Type
----------------|---------------------
contributorType | String[255] NOT NULL
key             | String[255]
fullName        | String[255]
familyName      | String[255]
givenName       | String[255]
affiliation     | String[1023]

(Note that affiliations and names of users may change over time.  Thats is why we need to keep track of affiliation and name at the time of the publication. Relying on the corresponding attributes of `User` only may not be enough.)

## `RelatedIdentifier`

Identifier of a related resource to a data publication

Constraint: `publication`, `identifier`, `relationType` 

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication

Other fields:

Field        | Type
-------------|---------------------
identifier   | String[255] NOT NULL
relationType | String[255] NOT NULL

## `FundingReference`

Information about financial support for a data publication

Constraint: `publication`, `funderName`, `awardNumber`

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication

Other fields:

Field            | Type
-----------------|---------------------
funderName       | String[255] NOT NULL
funderIdentifier | String[255]
awardNumber      | String[255] NOT NULL
awardTitle       | String[255]

**Comment by RKrahl** [comment]
Let me add two comments:

1. I proposed `String[4000]` as the type for `DataPublication.description`.  I blindly copied that from `Investigation.summary` in the current schema.  Still need to check wether this size is appropriate for all use cases.
2. In my proposal, I defined `FundingReference` having a many to one relationship with `DataPublication`.  This will be fine for the suggested publication workflow.  But if we decide that we want to record funding references for investigations too, we would need to add a little bit more effort by defining `FundingReference` to have two many to many relationships with `Investigation` and `DataPublication` respectively.

**Comment by RKrahl** [comment]
I currently work at implementing landing pages for data publications. It turns out that it would be very useful to add another attribute `RelatedIdentifier.fullReference` of type `String[511]`.

**Comment by RKrahl** [comment]
In the meanwhile, I implemented landing pages for data publications at HZB. You may take them as an example of what these schema extensions should be used for and why the individual properties would be needed.  See [ND000001](https://doi.org/10.5442/ND000001) and [ND000002](https://doi.org/10.5442/ND000002) for two production examples. For the moment,  the publication metadata are stored in a static file on the server. This should be moved into ICAT as soon as the proposed schema extensions are available.

In the light of experience from this prototype implementation, I'd like to revise the proposed schema extensions and suggest to add the following classes:

## `DataPublication`

A curated data publication

Constraint: `facility`, `doi`

Relationships:

Card | Class               | Field
-----|---------------------|---------------------
1,1  | Facility            | facility
1,1  | DataCollection      | content
0,*  | DataPublicationUser | users
0,*  | DataPublicationDate | dates
0,*  | RelatedIdentifier   | relatedIdentifiers
0,*  | FundingReference    | fundingReferences

Other fields:

Field           | Type                 | Description
----------------|----------------------|-----------------------------------------------
doi             | String[255] NOT NULL |
title           | String[255] NOT NULL |
publicationDate | Date NOT NULL        | Date when the data was made publicly available
subject         | String[1023]         | List of keywords
description     | String[4000]         | Abstract

## `DataPublicationUser`

Author, e.g. creator of a or contributor to a data publication

Constraint: `publication`, `user`, `contributorType` 

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication
1,1  | User            | user

Other fields:

Field           | Type                 | Description
----------------|----------------------|---------------------------------------------------
contributorType | String[255] NOT NULL | See DataCite property contributorType or "Creator"
key             | String[255]          | Defines an order among the contributors
fullName        | String[255]          |
familyName      | String[255]          |
givenName       | String[255]          |
affiliation     | String[1023]         |

## `DataPublicationDate`

A date relevant for the publication

Constraint: `publication`, `dateType` 

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication

Other fields:

Field    | Type                 | Description
---------|----------------------|-----------------------------------------
dateType | String[255] NOT NULL | See DataCite property dateType
date     | String[255] NOT NULL | Use ISO 8601 format, may also be a range

Possible values for dateType include "Accepted", "Available", "Created", "Submitted".

## `RelatedIdentifier`

Identifier of a related resource to a data publication

Constraint: `publication`, `identifier` 

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication

Other fields:

Field         | Type                 | Description
--------------|----------------------|-----------------------------------
identifier    | String[255] NOT NULL |
relationType  | String[255] NOT NULL | See DataCite property relationType
fullReference | String[1023]

Possible values for relationType include "IsCitedBy", "IsCompiledBy", "IsReferencedBy", "IsSupplementTo", "References".

## `FundingReference`

Information about financial support for a data publication

Constraint: `publication`, `funderName`, `awardNumber`

Relationships:

Card | Class           | Field
-----|-----------------|------------
1,1  | DataPublication | publication

Other fields:

Field            | Type
-----------------|---------------------
funderName       | String[255] NOT NULL
funderIdentifier | String[255]
awardNumber      | String[255] NOT NULL
awardTitle       | String[255]

**Comment by RKrahl** [comment]
I need make two more minor amendments to the proposal:

- the attribute name `DataPublicationUser.key` need to be changed, because KEY is a keyword in JPQL queries. Rename to `DataPublicationUser.orderKey`.

- I'd like to drop the `NOT NULL` condition for `DataPublication.publicationDate`. I originally proposed this, because `PublicationYear` is a mandatory property in DataCite, so we need this date in the final publication. But we also need to be able to store publications during the preparation phase, while they are not yet public. So we need a criterion to formulate access rules allowing read access to final publications and hiding not yet public ones. The easiest solution is to set `publicationDate` to NULL while the publication is not yet public. So this should be possible.

I edited my comment above accordingly to reflect these changes.

**Comment by RKrahl** [comment]
It has been suggested in the monthly meeting to add a property `affiliationIdentifier` to `DataPublicationUser`. I'm happy with that suggestion.

**Comment by dfq16044** [comment]
Here it is suggested that there is a relationship between the DataPublication and DataCollection.
Currently, many facilities are minting DOIs by:
- investigation (after an embargo period the data from an investigation will be made publicly available).
- data collection (datasets and datafiles): a user might want to mint a DOI for dataset/datafiles coming from different investigations or simply want to make some data from an investigation (not all) public before the embargo period.

**Comment by kevinphippsstfc** [comment]
There is already a `Publication` entity in the ICAT schema. The ISIS and Diamond ICATs have 1000+ entries in this table but they both look like they were done as a one off import a long time ago - 2007 for ISIS and 2011 for Diamond! I am not sure whether these records are being used anywhere.

So we need to decide whether to keep the original entity as well as the new one and if so, at least give the entities better descriptions in the documentation so that the distinction between the two is clear.

**Comment by dfq16044** [comment]
As far as I know the Publication table is not used at DLS. We have a separate database for Publications.

**Comment by RKrahl** [comment]
> Currently, many facilities are minting DOIs by:
> 
>     * investigation (after an embargo period the data from an investigation will be made publicly available).
> 
>     * data collection (datasets and datafiles): a user might want to mint a DOI for dataset/datafiles coming from different investigations or simply want to make some data from an investigation (not all) public before the embargo period.

Yes, and they may of course continue to do so, nothing in this proposal speaks against that.

This proposal is for a different use case, that is curated data publications. Curated means that all the publication metadata are properly collected and published together with the data on the publication landing pages and disseminated in the DataCite DOI metadata. Again, please have a look at HZB's publication landing pages for [doi:10.5442/ND000001](https://doi.org/10.5442/ND000001) and  [doi:10.5442/ND000002](https://doi.org/10.5442/ND000002) to see what I mean.

At the moment, we can't do this with ICAT, because we simply do not have any place in the ICAT schema to store the publication metadata. This proposal is about enabling this curated publication workflow, not about setting instructions on how DOI minting should be done in general.

**Comment by dfq16044** [comment]
I agree with you and we need it. The only problem is that the link is only with DataCollection but some facilities are minting DOIs at the investigation level. 
At DLS, we are not minting DOIs yet but I found that with the current schema as we don't have a snapshot of the user information then the information in the ICAT database will not be correct as a user might change name or affiliation. This schema change will potentially fix this problem but this would be better if this could be  linked to the DataCollection or Investigation.

**Comment by dfq16044** [comment]
> So we need to decide whether to keep the original entity as well as the new one and if so, at least give the entities better descriptions in the documentation so that the distinction between the two is clear.

I might be wrong but I think the original purpose of this table was to link journal paper with Investigation. Here what Rolf is proposing is to create entities for Data Publication. I would say that here in his proposal RelatedIdentifier will be the table closer to the Publication table in ICAT.

**Comment by RKrahl** [comment]
@kevinphippsstfc 

> There is already a `Publication` entity in the ICAT schema. The ISIS and Diamond ICATs have 1000+ entries in this table but they both look like they were done as a one off import a long time ago - 2007 for ISIS and 2011 for Diamond! I am not sure whether these records are being used anywhere.

I would say the existing `Publication` table and this proposal are unrelated, because they serve different use cases.

The `Publication` table, at least as I understand it, is for collecting references to publications that are _made elsewhere_, mostly journal articles that have been published as a result of an investigation. For this use case, it is largely enough to store the information needed to find and to identify that publication.

The proposed `DataPublication` and related tables are for data publications _made by the facility_ and published using ICAT. This requires the full set of bibliographic metadata to be stored in a structured way. This is also the reason why this proposal is limited to data publications as opposed to articles or other research output, because ICAT is about managing data. It will never fit to serve all sorts of publication workflows.

I don't believe it makes sense trying to squeeze these two use cases in the same data structures and trying to harmonize in any way the `Publication` table with `DataPublication` and related tables.

**Comment by RKrahl** [comment]
@dfq16044 

> I agree with you and we need it. The only problem is that the link is only with DataCollection but some facilities are minting DOIs at the investigation level.
> At DLS, we are not minting DOIs yet but I found that with the current schema as we don't have a snapshot of the user information then the information in the ICAT database will not be correct as a user might change name or affiliation. This schema change will potentially fix this problem but this would be better if this could be linked to the DataCollection or Investigation.

Two remarks on that:

1. As previously explained, the use case for these proposed schema extensions are curated data publications that comprise an extra step of properly collecting the bibliographic metadata. Our user do that when they want to publish a particular result that they obtained during an investigation. The most common case is a data publication that is the supplement to a journal article that is prepared in parallel. I'd argue that it is rather uncommon that users would want to do that for an investigation as a whole, because, during an investigation, generally a lot of measurements are done, including some try and error and searching for the right parameter range and only a subset of all that is relevant for the result the user wants to present for this publication. In contrary, users often create a new dedicated dataset, combining the relevant subset of raw data and adding the analysis performed for this particular paper for the purpose of such a data publication.

2. If you still want to publish an investigation as a whole, no problem, you can do that, using the data structures proposed above: you only need to create a new `DataCollection`, add all the datasets from the investigation and use that collection as the content of the new `DataPublication`.

That is exactly the reason why `DataPublication` relates to `DataCollection` and not to any other entity out of `Investigation`, `Dataset`, or `Datafile`, because this is the most versatile approach that supports all kinds of use cases.

**Comment by dfq16044** [comment]
DLS has not decided yet in the way they want to mint DOIs but currently ISIS and ESRF are minting DOIs per investigation (automated process). 
We can add all datasets in a DataCollection but we can have cases where we have thousands of datasets per investigation.

**Comment by RKrahl** [comment]
> DLS has not decided yet in the way they want to mint DOIs but currently ISIS and ESRF are minting DOIs per investigation (automated process).

For that automated process, this schema extension is not the right choice, this process only needs the `doi` attribute that is already present in `Investigation`.

> We can add all datasets in a DataCollection but we can have cases where we have thousands of datasets per investigation.

See, why this is most likely not suitable for a curated data publication.  But even then, what's wrong with a `DataCollection` having thousands of datasets?

**Comment by dfq16044** [comment]
It will probably be more performant if this is linked to one investigation instead of all datasets present in each investigation.

**Comment by RKrahl** [comment]
Why would a `DataPublication` relating to an investigation that in turn relates to thousands of datasets be more performant then a `DataPublication` relating to an `DataCollection` that in turn relates to thousands of datasets? It is exactly the same pattern.

**Comment by dfq16044** [comment]
I suppose if you link DataPublication to only DataCollection or Datasets and not Investigation, you will need to link InvestigationParameter at the Dataset level (by creating DatasetParameter) instead of having a single reference at the investigation level.

**Comment by RKrahl** [comment]
@dfq16044, I'm afraid, I don't understand what you are trying to do. In order to create a data publication landing page or to deliver DataCite metadata for a data publication, you don't need anything from the `Investigation` attributes or related objects. Please, again, have a look at the examples at [ND000001](https://doi.org/10.5442/ND000001) and [ND000002](https://doi.org/10.5442/ND000002) and tell me what you feel missing there.

**Comment by dfq16044** [comment]
This is the way you create DOIs at HZB, you are not doing at the investigation level. This will depend on the metadata that the facility wants to add in the corresponding DOI landing page. 
Furthermore when minting DOI, datacite has a field called Subject 0-n Subject, keyword, classification code, or key phrase describing the resource. If a facility decides to automatically create DOIs at the investigation level, we might want some keywords associated to the investigation be added to the DOI.

See those examples from ISIS and ESRF:
https://data.isis.stfc.ac.uk/doi/INVESTIGATION/83552727/
(information about instrument, visit id etc ...)
https://doi.esrf.fr/10.15151/ESRF-ES-71559333
(information about proposal, instrument, category ...)

I can understand that HZB view is to create DOIs manually but other facilities may have different approaches.

**Comment by RKrahl** [comment]
We are going around in circles. I repeat: the use case for these proposed schema extensions are curated data publications. For the automated process, this schema extension is not the right choice, this process only needs the `doi` attribute that is already present in `Investigation`.

> This is the way you create DOIs at HZB, you are not doing at the investigation level. This will depend on the metadata that the facility wants to add in the corresponding DOI landing page.
> Furthermore when minting DOI, datacite has a field called Subject 0-n Subject, keyword, classification code, or key phrase describing the resource. If a facility decides to automatically create DOIs at the investigation level, we might want some keywords associated to the investigation be added to the DOI.

That is why there is a `subject` attribute in the proposed `DataPublication` class.

> See those examples from ISIS and ESRF:
> https://data.isis.stfc.ac.uk/doi/INVESTIGATION/83552727/
> (information about instrument, visit id etc ...)
> https://doi.esrf.fr/10.15151/ESRF-ES-71559333
> (information about proposal, instrument, category ...)
> 
> I can understand that HZB view is to create DOIs manually but other facilities may have different approaches.

Yes. As you perfectly demonstrate with these examples, this approach already works fine with the existing schema. Nothing in this proposal prevents you from continuing to create DOIs in an automated manner at investigation level.

We have two different approaches to do data publications. One of them, the automated workflow minting DOIs at investigation level is already supported in the current schema. The other one, the curated data publication workflow is currently not. This proposal is about enabling the latter, not about inhibiting the former. If it gets implemented in ICAT, both will work.

> I would need to talk with our DBA to understand the implication of having all datasets from an investigation being associated to both DataCollection and Investigation in the case that we want to create DOIs per investigation.

I don't see any reason why you would want to do that.

**Comment by dfq16044** [comment]
I think that STFC will need to look at the way we can have snapshot of user affiliation for investigations as this is not available in the current ICAT schema.
Furthermore, we will need to see how we can link the citations from papers and databases (like PDB) with the investigation as it will just be done in the DataPublication ...
I believe this will need to be discussed with STFC at the next ICAT meeting.

**Comment by stuartpullinger** [comment]
Would it be possible to incorporate the Affiliation entity from #248? This would better handle the use case where a DataPublicationUser has more than one affiliation.

**Comment by RKrahl** [comment]
Yes, sure!  #248 and #249 are meant to amend #200. They are variants and of course, there is a whole lot of possible combinations of these variants. We will need to discuss this on Thursday and will hopefully arrive at a decision which of these variants we want to pursue.
