### ISSUE TITLE
ICAT schema: add DOI attribute to study 

### ISSUE THREAD

**Issue by gc-code** [icatproject/icat.server#216]
I would like to be able to create DOIs for a collection of investigations. The easiest way to do this with the current schema is to add a DOI attribute to the study table, which can link to multiple investigations.

**Comment by stuartpullinger** [comment]
I have named the field 'PID' rather than 'DOI' as PID is the more general term. Some entities in the schema have DOI as the field name. A future major release may change this so all entities use 'PID' instead.
