### ISSUE TITLE
ICAT schema: endDate is missing in Study

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#219]
While preparing python-icat for the upcoming icat.server 4.10 release and adopting the schema changes, I noticed that Study has a `startDate`, but no `endDate`. Is this intended? Or has `endDate` simply been forgotten?

**Comment by stuartpullinger** [comment]
Sorry - I don't have the historical knowledge to know if this was intended. It seems like am omission to me. It should be relatively easy to fix in 4.10.0.
