### ISSUE TITLE
Add a relationship between Dataset and Instrument

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#228]
In PaNOSC WP3 we are currently discussing the [API](https://github.com/panosc-eu/search-api) for the local metadata catalogues to be searched by the federated catalogue. While this discussion is not yet concluded, the [current draft for a data model](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md) envisages a relation between Dataset and Instrument.

In ICAT, we have that relation only indirectly via Investigation. This may be a problem, because the datasets within a single investigation may have been created with different instruments and there is no easy way to establish the information which dataset has been created at which instrument out of our current schema. For me it would make perfect sense to relate a dataset directly to the instruments that created it.

At least for HZB, that relationship should be many-to-many, because we have in general more then one single instrument being involved in a single measurement (e.g. beam line and experimental station).

**Comment by RKrahl** [comment]
In order to substantiate this proposal, I suggest to add a new class to the schema:

## `InstrumentDataset`

Represents a many-to-many relationship between an instrument and a dataset with data collected at that instrument

Constraint: `instrument`, `dataset`

Relationships:

Card | Class      | Field
-----|------------|-----------
1,1  | Instrument | instrument
1,1  | Dataset    | dataset

As an implicit consequence, a new one-to-many relationship `instrumentDatasets` with type `InstrumentDataset` would be added to both `Instrument` and `Dataset`.

**Comment by louise-davies** [comment]
I would suggest that the new class be named `DatasetInstrument` to match with the existing `InvestigationInstrument` class.

**Comment by RKrahl** [comment]
> I would suggest that the new class be named `DatasetInstrument` to match with the existing `InvestigationInstrument` class.

I'm happy with that suggestion.
