### ISSUE TITLE
Add volume and fileCount to Investigation and Dataset

### ISSUE THREAD

**Issue by antolinos** [icatproject/icat.server#238]
It has always been a sort of issue to get the calculation with the total volume of a number of files. We have solved it by storing these values as DataParameter and InvestigationParameters and they are recalculated any time a file, dataset or investigation is modified in ICAT

We can live without but it might be interesting to consider to add them as fields of the tables Investigation and Dataset.

Example:

Field | Type | Description
-- | -- | --
name | String [255] NOT NULL | A short name for the investigation
startDate | Date |  
doi | String [255] | The Digital Object Identifier associated with this investigation
summary | String [4000] | Summary or abstract
modId | String |  
releaseDate | Date | When the data will be made freely available
visitId | String [255] NOT NULL | Identifier for the visit to which this investigation is related
createId | String |  
createTime | Date |  
modTime | Date |  
endDate | Date |  
title | String [255] NOT NULL | Full title of the investigation
volume | Integer | Total volume of the investigation 
fileCount | Integer | Total number of files of the investigation

**Comment by RKrahl** [comment]
Note that this partly duplicates #233 which adds `Dataset.datasetSize` and `Investigation.investigationSize` but no `fileCount`.

**Comment by RKrahl** [comment]
@antolinos, would you agree to name that new attribute `Dataset.datasetSize` and `Investigation.investigationSize` respectively instead of `volume` as done in #233?

**Comment by antolinos** [comment]
> @antolinos, would you agree to name that new attribute `Dataset.datasetSize` and `Investigation.investigationSize` respectively instead of `volume` as done in #233?

Perfectly fine with me!!
