### ISSUE TITLE
Add a direct relationship between FacilityCycle and Investigation

### ISSUE THREAD

**Issue by tomhayter** [icatproject/icat.server#259]
In ISIS we currently have some investigations that fall outside of FacilityCycle dates. These gaps in between cycles can last up to a few months. All investigations belong to a cycle, but it is difficult to calculate which FacilityCycle an Investigation belongs to based on it's date. This causes issues when users try to access these investigations in topcat/datagateway.

Adding a direct many-to-one relationship between Investigation and FacilityCycle would help us solve this problem. My proposal is to add a `facilityCycle` field to the Investigation table. This means that even if the dates don't always match up, an Investigation can still belong to a FacilityCycle.

**Comment by RKrahl** [comment]
Note that this relation did exist in [ICAT 4.2.5](https://repo.icatproject.org/site/icat/server/4.2.5/icat.core/schema.html). It has been removed in 4.3.0. I don't remember the reason.

I'm indifferent to adding it again. In any case, it should be optional, as there are facilities (HZB) that do not use `FacilityCycle` at all.

**Comment by tomhayter** [comment]
After a little more investigation it looks like it would make more sense at ISIS if Investigations belonged to multiple cycles, as some of our investigations run over multiple years. Therefore, I'd like to suggest we make the direct relationship between Investigation and FacilityCycle a many-to-many relationship by adding an `InvestigationFacilityCycle` join table.

**Comment by agbeltran** [comment]
Included in 5.0.0
