### ISSUE TITLE
Temporarily disable failing test in TestRS

### ISSUE THREAD

**Issue by kevinphippsstfc** [icatproject/icat.server#289]
Whilst trying to fix #273 and reviewing the associated PR #275 it was found that different results were obtained by different people/setups and this is not yet fully understood but believed to be dependent on the test environment (OS, java version, payara version, database driver etc.) 

So that this issue does not hold up the release of ICAT 5, a decision was made at the collaboration meeting on 19th May to disable the failing part of the test for now to allow it to be fixed at a later date.

**Comment by RKrahl** [comment]
Close as `wontfix`, see comment in #290.
