### ISSUE TITLE
ICAT Restful API documentation is missing for icat.server 6.0

### ISSUE THREAD

**Issue by RKrahl** [icatproject/icat.server#310]
If you check the [landing page for the current icat.server version 6.0](https://repo.icatproject.org/site/icat/server/6.0.0/) and click on the [RESTful interface](https://repo.icatproject.org/site/icat/server/6.0.0/miredot/index.html) link, you get a 404. E.g. the Miredot generated docu is missing from the site. (The [corresponding link for icat.server 5.0.1](https://repo.icatproject.org/site/icat/server/5.0.1/miredot/index.html) works.)

I guess, the cause is related to the following error message that I get when trying to build icat.server 6.0:
```
[INFO] --- miredot-plugin:2.4.1-Java11:restdoc (miredot) @ icat.server ---
[WARNING] Miredot is unable to document the status codes of rest interfaces, unless a statusCodes-block is specified in pom.xml
[WARNING] Rest Framework not explicitly set, using JAX-RS by default.
[INFO] Building reflective model of API and reading annotations...
[ERROR] Your project doesn't contain any REST interfaces, so no output will be generated.
Maybe it is incorrectly configured.
```

**Comment by ajkyffin** [comment]
It looks like Miredot does not find any REST annotations because they have changed to the `jakarta` namespace and it is scanning for annotations from the `javax` namespace.

**Comment by moonraker595** [comment]
I've also noticed that the page doesn't render the text correctly and has no horizontal scroll, meaning some text gets cut off. I'm using Firefox v117.0.1 and Chrome v116.0.5845.179.
<img width="1280" alt="Screenshot 2023-09-18 at 16 44 21" src="https://github.com/icatproject/icat.server/assets/23454957/58bf963a-687c-4443-a690-55c39820259d">

**Comment by ajkyffin** [comment]
There is a new release of Miredot (2.4.3-Java11) that supports JakartaEE.

**Comment by ajkyffin** [comment]
I've made a PR (#316) that updates Miredot, and I've used it to regenerate the docs for 6.0.0. I don't want to merge it yet because I want to avoid changing the scope of the jakartaee-api dependency if possible.
